article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path("dashboard/",views.dashboard,name = "dashboard"),
    path("addarticle/",views.addArticle,name = "addarticle"),
    path("article/<int:id>",views.detail,name = "detail"),
    path("update/<int:id>",views.updateArticle,name = "update"),
    path("delete/<int:id>",views.deleteArticle,name = "delete"),
    path("",views.articles,name = "articles"),
    path("comment/<int:id>",views.addComment,name = "comment"),



]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from article import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.index, name="index"),
    path("about/",views.about, name="about"),
    path("articles/",include("article.urls")),
    path("user/",include("user.urls")),
   
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("register/",views.register,name = "register"),
    path("login/",views.loginUser,name = "login"),
    path("logout/",views.logoutUser,name = "logout"),



]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name="Yazar")
    title = models.CharField(max_length = 50,verbose_name="Başlık")
    #content = models.TextField(verbose_name="İçerik")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name="Makaleye Fotoğraf Ekleyin")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ["-created_date"]
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name ="Makale",related_name = "comments")
    comment_author = models.CharField(max_length =50,verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ["-comment_date"]

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

user/forms.py
from typing import Any
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı")
    password = forms.CharField(label = "Parola",widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50,label="Kullanıcı Adı")
    password = forms.CharField(max_length=20,label="Parola",widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label="Parola",widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar Eşleşmiyor")
        values = {
            "username" : username,
            "password" : password
        }
        return values

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article,Comment
from django.contrib.auth.decorators import login_required
# Create your views here.
def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles =Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    
    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})
def index(request):
    context = {
        "numbers":[1,2,3,4,5,6]
    }
    return render(request,"index.html",context)

def about(request):
    return render(request,"about.html")

def detail(request,id):
    return HttpResponse("Detail:"+str(id))
@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }

    return render(request,"dashboard.html",context)
@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit = False)
        article.author = request.user
        article.save()

        messages.success(request,"Makale Başarıyla Oluşturuldu")
        return redirect("article:dashboard")
    return render(request,"addarticle.html",{"form":form})
def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})
@login_required(login_url = "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit = False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale Başarıyla Güncellendi")
        return redirect("article:dashboard")
    return render(request,"update.html",{"form":form})
@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    article.delete()
    messages.success(request,"Makale Başarıyla Silindi")

    return redirect("article:dashboard")
def addComment(request,id):
    article = get_object_or_404(Article,id = id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author,comment_content = comment_content)
        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs = {"id":id}))

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
# Create your views here.

def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        newUser = User(username = username)
        newUser.set_password(password)
        newUser.save()
        login(request,newUser)
        messages.info(request,"Başarıyla Kayıt Oldunuz...")
        return redirect("index")
    context = {
        "form" : form
        }
    return render(request,"register.html",context)   
    """if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            newUser = User(username = username)
            newUser.set_password(password)
            newUser.save()
            login(request,newUser)
            return redirect("index")
        context = {
            "form" : form
        }
        return render(request,"register.html",context)
    else:
        form = RegisterForm()
        context = {
            "form" : form
        }
        return render(request,"register.html",context)"""
   
def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            messages.info(request,"Kullanıcı Adı veya Parola Hatalı...")
            return render(request,"login.html",context)
        messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        return redirect("index")

    return render(request,"login.html",context)
def logoutUser(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yaptınız")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}

{% block body %}

<h3>Hakkımızda</h3>
<hr>

<p>
“Türk Genci, devrimlerin ve cumhuriyetin sahibi ve bekçisidir. Bunların gereğine, doğruluğuna herkesten çok inanmıştır. Yönetim biçimini ve devrimleri benimsemiştir. Bunları güçsüz düşürecek en küçük ya da en büyük bir kıpırtı ve bir davranış duydu mu, “Bu ülkenin polisi vardır, jandarması vardır, ordusu vardır, adalet örgütü vardır” demeyecektir. Elle, taşla, sopa ve silahla; nesi varsa onunla kendi yapıtını koruyacaktır.
Polis gelecek, asıl suçluları bırakıp, suçlu diye onu yakalayacaktır. Genç, “Polis henüz devrim ve cumhuriyetin polisi değildir” diye düşünecek, ama hiç bir zaman yalvarmayacaktır. Mahkeme onu yargılayacaktır. Yine düşünecek, “demek adalet örgütünü de düzeltmek, yönetim biçimine göre düzenlemek gerek”
Onu hapse atacaklar. Yasal yollarla karşı çıkışlarda bulunmakla birlikte bana, başbakana ve meclise telgraflar yağdırıp, haksız ve suçsuz olduğu için salıverilmesine çalışılmasını, kayrılmasını istemeyecek. Diyecek ki, “ben inanç ve kanaatimin gereğini yaptım. Araya girişimde ve eylemimde haklıyım. Eğer buraya haksız olarak gelmişsem, bu haksızlığı ortaya koyan neden ve etkenleri düzeltmek de benim görevimdir.”
<p>

{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}


<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>Makale Oluştur</h3>
    <hr>
    <form method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form | crispy}}
    <br>
    <button type = "submit" class = "btn btn-danger">Makale Ekle</button>

    </form>
  </div>

</div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<div class = "row">
    <div class="col-md-8 offset-md-3">
    <div class="col-lg-8">
    <h3>Makaleler</h3>
    <hr>
    </div>
    </div>
</div>
<div class = "row">
    <div class="col-md-8 offset-md-3">
        <div class="col-lg-8">
            <form>
            {% csrf_token %}
                <input type="text" name = "keyword" class="input-sm" maxlength="64"  placeholder="Ara...">
                <button class="btn btn-lg btn-danger" type="submit">Ara</button>
            </form>
        </div>
    </div>
</div>
{% if articles %}
{% for article in articles  %}
<div class="row">
    <div class="col-md-8 offset-md-3">
            <div class="col-lg-8">

                <!-- the actual blog post: title/author/date/content -->
                <a href="{%url 'article:detail' article.id %}"> <h2>{{article.title}}</h2></a>
                <p class="lead">
                  {{article.author.username}} tarafından yayınlandı
                </p>
                <hr>
                <p>{{article.created_date}}</p>
                <hr>
                {% if article.article_image %}
                 <a href="/articles/article/{{article.id}}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
               
                {% endif %}
                
                <hr>
                <p class="lead">
                    {{article.content | safe | truncatewords:50}}
                </p>

                <a style ="float : right;" href="/articles/article/{{article.id}}" class ="btn btn-danger">Devamını Oku</a>
                

                
          
                <hr>

                

            </div>
    </div>
            
</div>
{% endfor %}

{% else %}
<div class = "row">
    <div class="col-md-8 offset-md-3">
        <div class="col-lg-8">
<div class = "alert alert-danger">
    Makale Bulunamadı
</div>
</div>
</div>
</div>
{% endif %}
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <small>{{request.user.username}}</small>
</p>
<hr>
<a class = "btn btn-danger" href = "/articles/addarticle">Makale Ekle</a>
<hr>
{% if articles %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Tarih</th>
      <th scope="col">Güncelle</th>
      <th scope="col">Sil</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles  %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td><a href="/articles/update/{{article.id}}" class = "btn btn-danger">Güncelle</a></td>
      <td><a href="/articles/delete/{{article.id}}" class = "btn btn-danger">Sil</a></td>
    </tr>
    {% endfor %}
   <!--- <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr> -->
    
  </tbody>
</table>

{% else %}
<div class = "alert alert-danger">
    Henüz bir makaleniz bulunmuyor...
</div>
{% endif %}



{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">
            <div class="col-lg-8">

                <!-- the actual blog post: title/author/date/content -->
                <h3>{{article.title}}</h3>
                <p class="lead">
                 by {{article.author.username}}
                </p>
                <hr>
                <p>{{article.created_date}}</p>
                <hr>
                {% if article.article_image %}
                <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
               
                {% endif %}
                
                <hr>
                <p class="lead">
                    {{article.content | safe}}
                </p>
                         
                <hr>
                <h4>Yorumlar</h4>
                <hr>
                {% if comments %}
                {% for  comment in comments %}
 
                <div class ="media mb-4">
                    <img class ="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50"  alt="">
                  <div class = "media-body">
                   <h5 class = "mt-0">{{comment.comment_author}}</h5>
                   {{comment.comment_date}}
                   <br>
                   {{comment.comment_content}}
                  </div>
                </div>
                {% endfor %}

                {% else %}
                <div class = "alert alert-danger">
                Bu makaleye hiç yorum yapılmamış. İlk yorum yapan siz olun.
                </div>
                {% endif %}

<div class="well">
                    <h4>Yorum Ekle:</h4>
                    <form method = "post" role="form" action = "{% url 'article:comment' article.id %}" >
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="formGroupExampleInput">İsim</label>
                            <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi Girin">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Yorum</label>
                            <textarea name = "comment_content" class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-danger">Ekle</button>
                    </form>
</div>
                

            </div>           
</div>

{% endblock body %}

templates/includes/navbar.html
<!---<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">-->
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <a class="navbar-brand" href="{%url 'index' %}">YB Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'about' %}">Hakkımızda</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'article:articles' %}">Makaleler</a>
          </li>  

        </ul>
        <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'article:dashboard' %}">Kontrol Paneli</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'user:logout' %}">Çıkış Yap</a>
          </li>
        {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'user:login' %}">Giriş Yap</a>
          </li>
        {% endif %}

        <li class="nav-item active">
            <a class="nav-link" href="{%url 'user:register' %}">Kayıt Ol</a>
          </li>

        
          
          
          
            

          
                 
        </ul>
        
      </div>
      
</nav>

templates/includes/posttemplate.html
<div class="row">
            <div class="col-lg-8">

                <!-- the actual blog post: title/author/date/content -->
                <h1>A Simple Blog Template for Bootstrap 3</h1>
                <p class="lead">by <a href="index.php">Start Bootstrap</a>
                </p>
                <hr>
                <p>
                    <span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>
                <hr>
                <img src="http://placehold.it/900x300" class="img-responsive">
                <hr>
                <p class="lead">Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>
                <p>You know, being a test pilot isn't always the healthiest business in the world.</p>
                <p>Cookie jelly beans soufflé icing. Gummi bears tootsie roll powder chupa chups cheesecake chocolate jelly-o lollipop lollipop. Halvah applicake chupa chups. Marshmallow chocolate jujubes icing lollipop gummi bears chupa chups pudding bonbon. Jelly beans jelly soufflé jujubes. Sesame snaps lollipop icing donut lemon drops soufflé.</p>
                <p>Donut caramels gingerbread. Sweet roll macaroon pastry cotton candy oat cake sesame snaps biscuit lemon drops dessert. Candy canes carrot cake danish carrot cake soufflé jelly chocolate cake muffin. Topping brownie donut. Oat cake marzipan dragée cheesecake. Donut chocolate cake jujubes tart dragée toffee.</p>
                <p>Tilefish electric knifefish salmon shark southern Dolly Varden. Pacific argentine tope golden shiner ilisha barreleye loosejaw catla, dogteeth tetra catfish tenpounder nase scup Ragfish brotula." Codlet brook lamprey pleco, Japanese eel convict cichlid titan triggerfish, plownose chimaera topminnow Black scalyfin. Walleye pollock, blue shark Sacramento blackfish prickleback airbreathing catfish yellowfin cutthroat trout, goby southern sandfish. North Pacific daggertooth dorab cepalin weever flying gurnard.</p>
                <p><strong>Placeholder text by:</strong>
                </p>
                <ul>
                    <li><a href="http://spaceipsum.com/">Space Ipsum</a>
                    </li>
                    <li><a href="http://cupcakeipsum.com/">Cupcake Ipsum</a>
                    </li>
                    <li><a href="http://tunaipsum.com/">Tuna Ipsum</a>
                    </li>
                </ul>

                <hr>

                <!-- the comment box -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form">
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

                <hr>

                <!-- the comments -->
                <h3>Start Bootstrap
                    <small>9:41 PM on August 24, 2013</small>
                </h3>
                <p>This has to be the worst blog post I have ever read. It simply makes no sense. You start off by talking about space or something, then you randomly start babbling about cupcakes, and you end off with random fish names.</p>

                <h3>Start Bootstrap
                    <small>9:47 PM on August 24, 2013</small>
                </h3>
                <p>Don't listen to this guy, any blog with the categories 'dinosaurs, spaceships, fried foods, wild animals, alien abductions, business casual, robots, and fireworks' has true potential.</p>

            </div>

            <div class="col-lg-4">
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                    <!-- /input-group -->
                </div>
                <!-- /well -->
                <div class="well">
                    <h4>Popular Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#dinosaurs">Dinosaurs</a>
                                </li>
                                <li><a href="#spaceships">Spaceships</a>
                                </li>
                                <li><a href="#fried-foods">Fried Foods</a>
                                </li>
                                <li><a href="#wild-animals">Wild Animals</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#alien-abductions">Alien Abductions</a>
                                </li>
                                <li><a href="#business-casual">Business Casual</a>
                                </li>
                                <li><a href="#robots">Robots</a>
                                </li>
                                <li><a href="#fireworks">Fireworks</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Bootstrap's default wells work great for side widgets! What is a widget anyways...?</p>
                </div>
                <!-- /well -->
            </div>
</div>

templates/index.html
{% extends "layout.html" %}

{% block body %}

    <div class="jumbotron text-center">
        <h3>Yazılım Bilimi Bloğuna Hoşgeldiniz</h3>
        <p>Bu blogda geliştiriciler olarak blog yazılarınız yer alır</p>
    </div>
    
    <p>
    {% if request.user.is_authenticated %}
        Giriş Yapılmış, {{request.user.username}}
    
    {% else %}
        Giriş Yapılmamış
    {% endif %}
    </p>

{% endblock  %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!---
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    -->
    <title>Ybblog</title>
</head>
<body>
    
    {%include "includes/navbar.html"%}

    
    <div style = "margin-top : 100px; margin-bottom : 100px;" class = "container">
        {% if messages %}
        
            {% for message in messages %}
            {% if message.tags == "info" %}
            <div class="alert alert-danger">{{ message }}</div>
            {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
            
            {% endfor %}
        
         {% endif %}
        {% block body %}
        
        {% endblock body %}
    
    </div>

    <script src = "{% static 'js/bootstrap.min.js' %}"></script>
    <script src = "{% static 'js/jquery-3.7.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    <!---
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> 
    -->  
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}


<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>Giriş Yap</h3>
    <hr>
    <form method = "post">
    {% csrf_token %}
    {{form | crispy}}
    <br>
    <button type = "submit" class = "btn btn-danger">Giriş Yap</button>

    </form>
  </div>

</div>


{% endblock body %}

h3

templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}


<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>Kayıt Ol</h3>
    <hr>
    <form method = "post">
    {% csrf_token %}
    {{form | crispy}}
    <br>
    <button type = "submit" class = "btn btn-danger">Kayıt Ol</button>

    </form>
  </div>

</div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}


<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>Makale Güncelle</h3>
    <hr>
    <form method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form | crispy}}
    <br>
    <button type = "submit" class = "btn btn-danger">Makale Güncelle</button>

    </form>
  </div>

</div>

{% endblock body %}